version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: disaster-monitoring-postgres
    environment:
      POSTGRES_DB: disaster_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - disaster-monitoring-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: disaster-monitoring-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - disaster-monitoring-network

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: disaster-monitoring-app
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: disaster_monitoring
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CACHE_TTL: 900
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      USGS_API_URL: https://earthquake.usgs.gov/fdsnws/event/1/query
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
      FLOOD_HIGH_THRESHOLD: 50
      EARTHQUAKE_HIGH_THRESHOLD: 5.0
      WILDFIRE_TEMP_THRESHOLD: 35
      WILDFIRE_HUMIDITY_THRESHOLD: 30
      RISK_FETCH_CRON: "*/15 * * * *"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - disaster-monitoring-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  disaster-monitoring-network:
    driver: bridge
